# nerdtree
[[plugins]]
repo = 'scrooloose/nerdtree'
on_cmd = 'NERDTree'
hook_add = '''
  let g:NERDTreeShowHidden = 1
  nnoremap <silent> <leader>nt :NERDTree<CR>
'''


# completion
# [[plugins]]
# repo = 'Shougo/neocomplete.vim'
# if = 'has("lua")'
# on_event = 'InsertEnter'
# hook_add = 'let g:enabled_neocomplete = 1'

# snippets
[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_ft = 'neosnippet'
on_event = 'InsertEnter'
depends = ['neosnippet-snippets']
hook_add = 'let g:enabled_neosnippet = 1'
[[plugins]]
# repo = 'Shougo/neosnippet-snippets'
repo = 'Rinse-495/neosnippet-snippets'
rev = 'adjust_coding_rules'

# syntaxes
[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]]
repo = 'vim-scripts/haskell.vim'
on_ft = 'haskell'

[[plugins]]
repo = 'othree/jsdoc-syntax.vim'
on_ft = 'javascript'

[[plugins]]
repo = 'Mizuchi/STL-Syntax'
on_ft = 'cpp'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = 'let g:vim_json_syntax_conceal = 0'

[[plugins]]
repo = 'udalov/kotlin-vim'
on_ft = 'kotlin'

# git
[[plugins]]
repo = 'tpope/vim-fugitive'
if = 'executable("git")'
on_event = 'VimEnter'

# help to write html
[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = 'html'

# utils
[[plugins]]
repo = 'itchyny/lightline.vim'
on_event = 'VimEnter'
hook_add = 'let g:enabled_lightline = 1'

[[plugins]]
repo = 'tpope/vim-surround'
on_event = 'VimEnter'

[[plugins]]
repo = 'soramugi/auto-ctags.vim'
on_event = 'VimEnter'
hook_add = '''
  let g:auto_ctags_directory_list = ['.git']
  let g:auto_ctags_tags_args = '--tag-relative --recurse --sort=yes --extra=+f'
'''

[[plugins]]
repo = 'rhysd/wandbox-vim'
on_cmd = 'Wandbox'
hook_add = 'let g:enabled_wandbox_vim = 1'

[[plugins]]
repo = 'roman/golden-ratio'
on_event = 'VimEnter'

[[plugins]]
repo = 'junegunn/fzf.vim'
on_event = 'VimEnter'
if = 'executable("fzf")'
