# dein
[[plugins]]
repo = 'Shougo/dein.vim'

# colorschemes
[[plugins]]
repo = 'AlessandroYorba/Alduin'
if = 'has("gui_running")'
hook_add = '''
  au DeinAutoCmd VimEnter * nested colorscheme alduin
'''

# util
[[plugins]]
repo = 'Yggdroot/indentLine'
